# Generated by Django 3.2.3 on 2021-09-24 11:00

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "hr_groups",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("title", models.CharField(max_length=255, null=True)),
                ("descriptions", models.TextField(blank=True, null=True)),
                ("repeat", models.BooleanField(default=False)),
                ("start_year", models.IntegerField(null=True)),
                ("end_year", models.IntegerField(null=True)),
                ("count", models.IntegerField(default=0, null=True)),
                ("calendar_id", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "hr_office_holiday",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "expired_annual_leave_last_year",
                    models.IntegerField(blank=True, default=6, null=True),
                ),
                ("established_date", models.DateField(default=datetime.date.today)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office",
                        to="api_office.group",
                    ),
                ),
            ],
            options={
                "db_table": "hr_offices",
            },
        ),
    ]
