# Generated by Django 3.2.3 on 2021-09-10 10:23

from django.db import migrations


def initial_group_data(apps, schema_editor):
    group_model = apps.get_model("api_office", "Group")
    office_model = apps.get_model("api_office", "Office")
    root_group = group_model(
        name="Paradox Company",
        email="general@paradox.ai",
        manager=None,
        parent_group=None,
    )
    root_group.save()
    asia_group = group_model(
        name="Asia", email="asia@paradox.ai", manager=None, parent_group=root_group
    )
    asia_group.save()
    vietnam_group = group_model(
        name="Vietnam",
        email="vietnam@paradox.com",
        manager=None,
        parent_group=asia_group,
    )
    vietnam_group.save()
    offices = [
        office_model(
            name="Nguyễn Hữu Thọ",
            address="460 Nguyễn Hữu Thọ, Khuê Trung, Cẩm Lệ, Đà Nẵng, Việt Nam",
            email="nlb_office@paradox.ai",
            group=vietnam_group,
        ),
    ]
    office_model.objects.bulk_create(offices)


class Migration(migrations.Migration):
    dependencies = [
        ("api_office", "0002_initial"),
    ]

    operations = [migrations.RunPython(initial_group_data, migrations.RunPython.noop)]
