# Generated by Django 3.2.3 on 2021-09-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="provider",
            table="hr_provider",
        ),
    ]
