# Generated by Django 3.2.3 on 2021-09-08 13:54

from api_session.constants import WorkDayChoices
from common.constants.workday_constants import Workday
from django.db import migrations


def initial_sessions(apps, schema_editor):
    session_model = apps.get_model("api_session", "Session")
    office_model = apps.get_model("api_office", "Office")
    sessions = []

    offices = office_model.objects.all()

    for office in offices:
        for choice in WorkDayChoices.choices:
            dow = choice[0]

            if dow in [WorkDayChoices.SATURDAY, WorkDayChoices.SUNDAY]:
                continue

            morning_session = session_model(
                start_time=Workday.DEFAULT_START_HOUR,
                end_time=Workday.DEFAULT_END_HOUR_MORNING,
                dow=dow,
                office=office,
            )
            afternoon_session = session_model(
                start_time=Workday.DEFAULT_START_HOUR_AFTERNOON,
                end_time=Workday.DEFAULT_END_HOUR,
                dow=dow,
                office=office,
            )
            sessions.append(morning_session)
            sessions.append(afternoon_session)

    session_model.objects.bulk_create(sessions)


class Migration(migrations.Migration):
    dependencies = [
        ("api_session", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(initial_sessions, migrations.RunPython.noop),
    ]
