# Generated by Django 3.2.3 on 2021-09-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_event", "0001_initial"),
        ("api_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_user.profile"
            ),
        ),
    ]
