# Generated by Django 3.2.3 on 2021-09-02 16:03

from django.db import migrations


def initial_provider(apps, schema_editor):
    provider_model = apps.get_model("api_providers", "Provider")
    providers = []

    provider_tri = provider_model(
        name="A Tri",
        phone="0123456789",
        budget="15000",
        description="Nothing",
        address="10/5 Phan Đình Phùng, Hải Châu 1, Đà Nẵng",
        link="https://hrm.dev.damelagi.org/",
    )
    provider_jins = provider_model(
        name="Jins",
        phone="0123456789",
        budget="25000",
        description="Nothing",
        address="10/6 Phan Đình Phùng, Hải Châu 1, Đà Nẵng",
        link="https://hrm.dev.damelagi.org/",
    )
    providers.extend([provider_tri, provider_jins])
    provider_model.objects.bulk_create(providers)

    lunch_model = apps.get_model("api_lunch", "Lunch")
    lunch_now = lunch_model(note="Món chính : ", provider=provider_tri)
    lunch_now.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_lunch", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(initial_provider, migrations.RunPython.noop),
    ]
