# Generated by Django 3.2.3 on 2021-10-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_providers", "0002_alter_provider_table"),
        ("api_lunch", "0002_migrate_template_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunch",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_providers.provider",
            ),
        ),
    ]
