# Generated by Django 3.2.3 on 2022-01-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_workday", "0003_alter_remainleave_year"),
        ("api_slackbot", "0002_auto_20220119_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templeaverequest",
            name="leave_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_workday.leavetype",
            ),
        ),
    ]
