# Generated by Django 3.2.3 on 2022-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_slackbot", "0003_alter_templeaverequest_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="templeaverequest",
            name="from_date",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="templeaverequest",
            name="from_time",
            field=models.CharField(
                choices=[("08:00", "08:00"), ("13:30", "13:30")],
                default="08:00",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="templeaverequest",
            name="to_date",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="templeaverequest",
            name="to_time",
            field=models.CharField(
                choices=[("12:00", "12:00"), ("17:30", "17:30")],
                default="17:30",
                max_length=255,
            ),
        ),
    ]
