# Generated by Django 3.2.3 on 2022-02-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_slackbot", "0004_auto_20220208_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="templeaverequest",
            name="full_day_leave_lunch_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="templeaverequest",
            name="lunch_status",
            field=models.BooleanField(default=False),
        ),
    ]
