# Generated by Django 3.2.3 on 2022-01-12 13:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_team", "0003_auto_20210927_1252"),
        ("api_user", "0003_auto_20211011_0905"),
        ("api_office", "0004_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationTemplate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_templates",
                        to="api_office.office",
                    ),
                ),
            ],
            options={
                "db_table": "hr_evaluation_template",
            },
        ),
        migrations.CreateModel(
            name="EvaluationTemplateCompetence",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("competence", models.TextField(blank=True, null=True)),
                (
                    "evaluation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="api_probation.evaluationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "hr_evaluation_template_competence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationTemplateOverallComment",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("term", models.TextField(blank=True, null=True)),
                (
                    "evaluation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_comments",
                        to="api_probation.evaluationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "hr_evaluation_template_overall_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationTemplateOverallCommentAssessorRole",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "overall_comment_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "overall_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessor_roles",
                        to="api_probation.evaluationtemplateoverallcomment",
                    ),
                ),
            ],
            options={
                "db_table": "hr_evaluation_template_overall_comment_assessor_role",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Probation",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("probation_end_date", models.DateField(null=True)),
                ("signing_official_labor_contract", models.BooleanField(default=False)),
                ("labor_contract_term", models.CharField(max_length=255, null=True)),
                (
                    "other_actions_and_updates",
                    models.CharField(max_length=255, null=True),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probations",
                        to="api_probation.evaluationtemplate",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probations",
                        to="api_team.team",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probations",
                        to="api_user.titles",
                    ),
                ),
            ],
            options={
                "db_table": "hr_probation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProbationOverallComment",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("score", models.IntegerField()),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessors_probation_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation_template_overall_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_overall_comments",
                        to="api_probation.evaluationtemplateoverallcomment",
                    ),
                ),
                (
                    "evaluation_template_overall_comment_assessor_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_overall_comments",
                        to="api_probation.evaluationtemplateoverallcommentassessorrole",
                    ),
                ),
                (
                    "probation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_comments",
                        to="api_probation.probation",
                    ),
                ),
            ],
            options={
                "db_table": "hr_probation_overall_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProbationCompetence",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("score", models.IntegerField()),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessors_probation_competencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_competencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation_template_competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_competencies",
                        to="api_probation.evaluationtemplateoverallcomment",
                    ),
                ),
                (
                    "evaluation_template_competence_assessor_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_competencies",
                        to="api_probation.evaluationtemplateoverallcommentassessorrole",
                    ),
                ),
                (
                    "probation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="api_probation.probation",
                    ),
                ),
            ],
            options={
                "db_table": "hr_probation_competence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationTemplateCompetenceAssessorRole",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "assessor_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "evaluation_competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessor_roles",
                        to="api_probation.evaluationtemplatecompetence",
                    ),
                ),
            ],
            options={
                "db_table": "hr_evaluation_template_competence_assessor_role",
                "ordering": ["-created_at"],
            },
        ),
    ]
