# Generated by Django 3.2.9 on 2022-01-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_probation", "0002_auto_20220118_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="probation",
            name="labor_contract_term",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="probation",
            name="other_actions_and_updates",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="probation",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="probation",
            name="signing_official_labor_contract",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="probationcompetence",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="probationoverallcomment",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
