# Generated by Django 3.2.9 on 2022-02-10 14:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_probation", "0004_auto_20220125_1140"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProbationReminder",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reminder_date", models.DateField(blank=True, null=True)),
                ("reminder_duration", models.IntegerField(default=1)),
                (
                    "duration_time_unit",
                    models.CharField(
                        choices=[("day", "day"), ("week", "week")], max_length=10
                    ),
                ),
                ("reminder_status", models.BooleanField(default=False)),
                (
                    "probation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="api_probation.probation",
                    ),
                ),
            ],
            options={
                "db_table": "hr_probation_reminder",
                "ordering": ["-created_at"],
            },
        ),
    ]
