# Generated by Django 3.2.9 on 2022-02-11 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_probation", "0005_probationreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="probation",
            name="probation_line_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="probation_line_manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
