# Generated by Django 3.2.3 on 2022-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_probation", "0007_probationreminder_calendar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="probationreminder",
            name="duration_time_unit",
            field=models.CharField(choices=[("day", 1), ("week", 7)], max_length=10),
        ),
    ]
