# Generated by Django 3.2.9 on 2022-02-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_probation", "0008_alter_probationreminder_duration_time_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="probationreminder",
            name="duration_time_unit",
        ),
        migrations.RemoveField(
            model_name="probationreminder",
            name="reminder_duration",
        ),
    ]
