# Generated by Django 3.2.3 on 2022-03-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0004_remove_titles_weight"),
        ("api_probation", "0011_probation_self_evaluation_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="probation",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="probations",
                to="api_user.titles",
            ),
        ),
    ]
