# Generated by Django 3.2.3 on 2022-03-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_probation", "0012_alter_probation_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluationtemplatecompetence",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="evaluationtemplatecompetenceassessorrole",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="evaluationtemplateoverallcomment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="evaluationtemplateoverallcommentassessorrole",
            options={"ordering": ["created_at"]},
        ),
    ]
