# Generated by Django 3.2.9 on 2022-03-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_team", "0004_alter_team_team_leader"),
        ("api_probation", "0013_auto_20220325_1549"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="probation",
            name="title",
        ),
        migrations.AlterField(
            model_name="probation",
            name="probation_line_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="probation_line_manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="probation",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="probations",
                to="api_team.team",
            ),
        ),
    ]
