from .banks import BankViewSet
from .titles import TitleViewSet
from .photo import PhotoViewSet
from .profile import ProfileViewSet
from .user import UserViewSet
from .user_banks import UserBankViewSet
from .user_education import UserEducationViewSet
from .user_contact import UserContactViewSet
from .user_family_members import UserFamilyMembersViewSet
from .user_identity import UserIdentityViewSet
from .user_insurance import UserInsuranceViewSet
from .roles import RoleViewSet
