# Generated by Django 3.2.3 on 2021-09-24 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("team_name", models.CharField(max_length=255, unique=True)),
                (
                    "team_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "slack_channel",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "db_table": "hr_teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hr_team_members",
            },
        ),
    ]
