# Generated by Django 3.2.3 on 2021-09-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_office", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembers",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teammembers",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="api_team.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="api_office.office",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_leader",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
