# Generated by Django 3.2.3 on 2021-09-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_office", "0004_department"),
        ("api_team", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="api_office.department",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="api_office.group",
            ),
        ),
    ]
