# Generated by Django 3.2.3 on 2022-03-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_team", "0003_auto_20210927_1252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
