# Generated by Django 3.2.3 on 2022-01-11 15:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="WfhRequest",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_user.user",
                    ),
                ),
            ],
            options={
                "db_table": "hr_wfh_request",
            },
        ),
        migrations.CreateModel(
            name="WfhDate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("lunch", models.BooleanField(default=False)),
                (
                    "wfh_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wfh_date",
                        to="api_wfh.wfhrequest",
                    ),
                ),
            ],
            options={
                "db_table": "hr_wfh_date",
                "ordering": ["-date"],
            },
        ),
    ]
