# Generated by Django 3.2.3 on 2021-05-28 08:22
from core.settings.base import APP_NAME, DEFAULT_CLIENT_ID, DEFAULT_CLIENT_SECRET
from django.db import migrations
from django.db.models import Q
from oauth2_provider.models import AbstractApplication


def add_application(apps, schema_editor):
    Application = apps.get_model("api_oauth2", "Application")
    exist_app = Application.objects.filter(
        Q(name=APP_NAME), Q(client_id=DEFAULT_CLIENT_ID)
    ).exists()
    if not exist_app:
        Application.objects.create(
            client_id=DEFAULT_CLIENT_ID,
            client_type="confidential",
            authorization_grant_type="password",
            client_secret=DEFAULT_CLIENT_SECRET,
            name=APP_NAME,
            algorithm=AbstractApplication.RS256_ALGORITHM,
            scope="__all__",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api_oauth2", "0002_auto_20210704_1018"),
    ]
    operations = [migrations.RunPython(add_application, migrations.RunPython.noop)]
