# Generated by Django 3.2.3 on 2021-09-24 11:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                ("descriptions", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_count", models.BooleanField(default=True)),
                ("days", models.IntegerField(default=1, null=True)),
            ],
            options={
                "db_table": "hr_leave_type",
                "ordering": ["leave_type_group"],
            },
        ),
        migrations.CreateModel(
            name="LeaveTypeGroup",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                ("is_company_pay", models.BooleanField(default=True)),
                ("is_insurance_pay", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_leave_type_group",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestOff",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.FloatField(default=0)),
                (
                    "leave_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_workday.leavetype",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_user.profile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_request_off",
            },
        ),
        migrations.CreateModel(
            name="RequestDetail",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("comment", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(max_length=255, null=True)),
                (
                    "approve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approve_id",
                        to="api_user.profile",
                    ),
                ),
                (
                    "request_off",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_detail",
                        to="api_workday.requestoff",
                    ),
                ),
            ],
            options={
                "db_table": "hr_request_detail",
            },
        ),
        migrations.CreateModel(
            name="RemainLeave",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("year", models.IntegerField(default=2021)),
                ("annual_leave", models.FloatField(default=0)),
                ("annual_leave_last_year", models.FloatField(default=0)),
                ("current_days_off", models.FloatField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_user.profile",
                    ),
                ),
            ],
            options={
                "db_table": "hr_remain_year",
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="leavetype",
            name="leave_type_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_types",
                to="api_workday.leavetypegroup",
            ),
        ),
        migrations.CreateModel(
            name="DateOff",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(null=True)),
                (
                    "type",
                    models.CharField(default="All day", max_length=255, null=True),
                ),
                ("lunch", models.BooleanField(default=False)),
                (
                    "request_off",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_off",
                        to="api_workday.requestoff",
                    ),
                ),
            ],
            options={
                "db_table": "hr_date_off",
                "ordering": ["-date"],
            },
        ),
    ]
