# Generated by Django 3.2.3 on 2021-09-02 16:03

from django.db import migrations


def initial_leave_type(apps, schema_editor):
    leave_type_group_model = apps.get_model("api_workday", "LeaveTypeGroup")
    leave_type_model = apps.get_model("api_workday", "LeaveType")
    leave_type_groups = []
    leave_types = []

    business_pay = leave_type_group_model(
        name="Paid by Business", is_company_pay=True, is_insurance_pay=False
    )
    social_insurance_pay = leave_type_group_model(
        name="Paid by Social Insurance", is_company_pay=False, is_insurance_pay=True
    )
    unpaid_leave = leave_type_group_model(
        name="Unpaid Leave", is_company_pay=False, is_insurance_pay=False
    )
    leave_type_groups.extend([business_pay, social_insurance_pay, unpaid_leave])
    leave_type_group_model.objects.bulk_create(leave_type_groups)

    leave_type_annual_leave = leave_type_model(
        name="Annual Leave",
        leave_type_group=business_pay,
        descriptions="Nghỉ phép hàng năm, 12 ngày",
        days=12,
    )
    leave_type_marriage = leave_type_model(
        name="The Employees Marriage",
        leave_type_group=business_pay,
        descriptions="Kết hôn của nhân viên",
        days=3,
    )
    leave_type_marriage_children = leave_type_model(
        name="Marriage of Employees' children",
        leave_type_group=business_pay,
        descriptions="Con của nhân viên kết hôn",
        days=1,
    )
    leave_type_funeral = leave_type_model(
        name="Funeral Leave",
        leave_type_group=business_pay,
        descriptions="Tang lễ của cha/mẹ/vợ/chồng/con",
        days=3,
    )
    leave_type_paternity = leave_type_model(
        name="Paternity Leave",
        leave_type_group=social_insurance_pay,
        descriptions="Nghỉ sinh con, dành cho bố",
        is_count=False,
        days=5,
    )
    leave_type_maternity = leave_type_model(
        name="Maternity Leave",
        leave_type_group=social_insurance_pay,
        descriptions="Nghỉ sinh con, dành cho mẹ. Thường là 6 tháng",
        is_count=False,
        days=120,
    )
    leave_type_sick = leave_type_model(
        name="Sick Leave",
        leave_type_group=social_insurance_pay,
        descriptions="Nghỉ do đau ốm",
        is_count=False,
        days=5,
    )
    leave_type_other = leave_type_model(
        name="Others",
        leave_type_group=unpaid_leave,
        descriptions="Trường hợp này nhân viên nhập lý do nghỉ",
        is_count=False,
        days=5,
    )
    leave_types.extend(
        [
            leave_type_annual_leave,
            leave_type_marriage,
            leave_type_marriage_children,
            leave_type_funeral,
            leave_type_paternity,
            leave_type_maternity,
            leave_type_sick,
            leave_type_other,
        ]
    )
    leave_type_model.objects.bulk_create(leave_types)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_workday", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(initial_leave_type, migrations.RunPython.noop),
    ]
