# Generated by Django 3.2.3 on 2022-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_workday", "0002_migrate_template_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remainleave",
            name="year",
            field=models.IntegerField(default=2022),
        ),
    ]
