# Generated by Django 3.2.3 on 2022-07-26 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_add_role_team_leader'),
        ('api_workday', '0003_alter_remainleave_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='')),
            ],
            options={
                'db_table': 'hr_bonus_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusLeave',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField(default='')),
                ('given_leave', models.FloatField(default=0.5)),
                ('bonus_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_workday.bonustype')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.profile')),
            ],
            options={
                'db_table': 'hr_bonus_leave',
                'ordering': ['-created_at'],
            },
        ),
    ]
