# Generated by Django 3.2.3 on 2022-07-28 10:22

import django.db.models.deletion
from common.constants.user_constants import TitleConstant
from common.constants.workday_constants import LeaveTypeConstant
from django.db import migrations, models


def initial_leave_type_titles(apps, schema_editor):
    leave_type_model = apps.get_model('api_workday', 'LeaveType')
    title_model = apps.get_model('api_user', 'Titles')
    leave_types = leave_type_model.objects.all()
    titles = title_model.objects.all()

    for leave_type in leave_types:
        if leave_type.name == LeaveTypeConstant.ANNUAL_LEAVE:
            leave_type.approval_title = titles.filter(title=TitleConstant.TEAM_LEADER).get()
        else:
            leave_type.approval_title = titles.filter(title=TitleConstant.HEAD_OF_HR_AND_COMMUNICATION).get()
    leave_type_model.objects.bulk_update(
        leave_types, ["approval_title"])


class Migration(migrations.Migration):
    dependencies = [
        ('api_user', '0006_add_role_team_leader'),
        ('api_workday', '0003_alter_remainleave_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='approval_title',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='leave_types',
                to='api_user.titles'),
        ),
        migrations.RunPython(initial_leave_type_titles, migrations.RunPython.noop),
    ]
