# Generated by Django 3.2.3 on 2022-08-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_workday', '0004_leavetype_approval_title'),
        ('api_workday', '0005_migrate_bonus_leave'),
    ]

    operations = [
    ]
