# Generated by Django 3.2.3 on 2022-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_workday', '0006_merge_20220805_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonustype',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
