# Generated by Django 3.2.3 on 2022-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_workday', '0008_alter_bonusleave_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustype',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
