# Generated by Django 3.2.3 on 2022-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_workday', '0009_alter_bonustype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusleave',
            old_name='given_leave',
            new_name='bonus_days',
        ),
        migrations.AddField(
            model_name='bonusleave',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
