# Generated by Django 3.2.3 on 2022-03-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0003_auto_20211011_0905"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titles",
            name="weight",
        ),
    ]
