# Generated by Django 2.2.7 on 2020-09-15 02:46

from django.db import migrations


def add_role_leader(apps, schema_editor):

    Role = apps.get_model("api_user", "Role")
    Team = apps.get_model("api_team", "Team")
    team_leader_ids = list(Team.objects.all().values_list("team_leader", flat=True))
    leader_role, created = Role.objects.get_or_create(
        name="Team Leader",
        description="Access for team leader.",
        scope="team:create team:view team:edit_my_team",
    )
    leader_role.users.add(*team_leader_ids)
    leader_role.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [("api_user", "0005_auto_20220324_1018")]

    operations = [
        migrations.RunPython(add_role_leader, migrations.RunPython.noop),
    ]
