# Generated by Django 3.2.3 on 2022-09-14 15:20

from django.db import migrations, models
from django.db.models import Q


def remove_duplicate_super_admin_roles(apps, schema_editor):
    role = apps.get_model("api_user", "role")
    duplicated_super_admin_roles = role.objects.filter((Q(name='Super Administrator')) & ~Q(scope='__all__'))
    if duplicated_super_admin_roles:
        duplicated_super_admin_roles.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api_user', '0006_add_role_team_leader'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_super_admin_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
