# Generated by Django 3.2.3 on 2022-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'title')},
        ),
    ]
