# Generated by Django 3.2.3 on 2022-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_elearning', '0002_auto_20220727_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('DOCS', 'DOCS'), ('SLIDE', 'SLIDE')], default='VIDEO',
                                   max_length=50),
        ),
    ]
