# Generated by Django 3.2.3 on 2022-08-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0004_auto_20220810_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='cover_image',
            new_name='video',
        ),
    ]
