# Generated by Django 3.2.3 on 2022-08-11 16:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0005_rename_cover_image_lesson_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('script_at_second', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hr_transcripts',
                'ordering': ['script_at_second'],
            },
        ),
    ]
