# Generated by Django 3.2.3 on 2022-08-23 10:18

import api_elearning.models.attachment
import api_elearning.models.course
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_elearning', '0006_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='references',
        ),
        # migrations.RemoveField(
        #     model_name='course',
        #     name='topic',
        # ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='last_modifier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='last_modifier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_courses', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='course',
        #     name='topics',
        #     field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='api_elearning.Topic'),
        # ),
        migrations.AddField(
            model_name='lesson',
            name='last_modifier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=api_elearning.models.course.name_file),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AlterField(
        #     model_name='course',
        #     name='title',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='chapter',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='course',
        #     unique_together=set(),
        # ),
        migrations.AlterModelTable(
            name='chapter',
            table='el_chapters',
        ),
        migrations.AlterModelTable(
            name='course',
            table='el_courses',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='el_lessons',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='el_topics',
        ),
        migrations.AlterModelTable(
            name='transcript',
            table='el_transcripts',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True)),
                ('mine_type', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('length', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'el_attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
