# Generated by Django 3.2.3 on 2022-08-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0007_auto_20220818_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='next_lesson_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_elearning.lesson'),
        ),
    ]
