# Generated by Django 3.2.3 on 2022-08-23 13:55

from django.db import migrations, models
import api_elearning.models.attachment
import django.db.models.deletion
from django.conf import settings



class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0008_auto_20220823_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True,
                                   upload_to=api_elearning.models.attachment.upload_path),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='next_chapter_id',
            field= models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                     to='api_elearning.chapter')
        ),
        migrations.AddField(
            model_name='attachment',
            name='path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
