# Generated by Django 3.2.3 on 2022-08-24 03:41

from django.db import migrations, models

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0009_auto_20220823_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='next_chapter_id',
            new_name='next_chapter',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='api_elearning.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
    ]
