# Generated by Django 3.2.3 on 2022-08-31 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0012_auto_20220825_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentChapterLessonAttachment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_time', models.TimeField(blank=True, null=True)),
                ('current_page', models.IntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('assignment_chapter_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_chapter_lesson_attachments', to='api_elearning.assignmentchapterlesson')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attachments', to='api_elearning.attachment')),
            ],
            options={
                'db_table': 'el_assignment_chapter_lesson_attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
