# Generated by Django 3.2.3 on 2022-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0013_assignmentchapterlessonattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='forced_read',
            field=models.BooleanField(default=False),
        ),
    ]
