# Generated by Django 3.2.3 on 2022-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_elearning', '0014_attachment_forced_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentchapter',
            name='previous_assignment_chapter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignmentchapterlesson',
            name='previous_assignment_chapter_lesson_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
