# Generated by Django 3.2.3 on 2022-09-14 09:11

from django.db import migrations


def initial_data(apps, schema_editor):
    question_type_model = apps.get_model("api_elearning", "QuestionType")

    multiple_choice = question_type_model(name="MULTIPLE CHOICE",
                                          description="Multiple Choice")

    single_choice = question_type_model(name="SINGLE CHOICE",
                                        description="Single Choice")

    existed_type = question_type_model.objects.filter()
    if not existed_type:
        multiple_choice.save()
        single_choice.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api_elearning', '0015_auto_20220912_2132'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
