# Generated by Django 3.2.3 on 2022-09-15 15:38

from django.conf import settings
from django.db import migrations


def add_default_responser(apps, schema_editor):
    quiz = apps.get_model("api_elearning", "Quiz")
    user = apps.get_model("api_user", "User")
    super_user = user.objects.filter(is_superuser=True)
    if super_user:
        responser_default_id = super_user.first().pk
        quiz.objects.filter(responser_id=None).update(responser_id=responser_default_id)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_elearning', '0017_auto_20220914_1115'),
    ]

    operations = [
        migrations.RunPython(add_default_responser, migrations.RunPython.noop)
    ]
