# Generated by Django 3.2.3 on 2021-09-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_skill", "0003_skilltarget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skilldefinition",
            options={"ordering": ["skill"]},
        ),
    ]
