# Generated by Django 3.2.3 on 2022-03-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0004_remove_titles_weight"),
        ("api_skill", "0004_alter_skilldefinition_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleskill",
            name="title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="title_skills",
                to="api_user.titles",
            ),
        ),
    ]
