# Generated by Django 3.2.3 on 2021-10-05 14:38

import api_seat_map.models.object_type
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "svg_file",
                    models.FileField(
                        upload_to=api_seat_map.models.object_type.name_file,
                        validators=[
                            api_seat_map.models.object_type.validate_svg_extension
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "hr_seat_map_object_type",
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("offset_x", models.FloatField()),
                ("offset_y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("prioritized", models.IntegerField(default=0)),
                (
                    "managed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_objects",
                        to="api_seat_map.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "hr_seat_map_object",
            },
        ),
    ]
